!includeurl  https://raw.githubusercontent.com/nmshd/nmshd.github.io/main/diagrams/styles.iuml

@startuml Test

participant "App" as app
participant "Backbone" as backbone

app -> backbone: Test

@enduml
