# ATTENTION: Do NOT use this file in public or production scenarios! It may contain insecure or unstable configuration.

services:
  connector:
    container_name: connector
    image: ghcr.io/nmshd/connector:<version-or-latest> # specify a tag (e.g. 1.0.0) or use the 'latest' tag
    environment:
      CUSTOM_CONFIG_LOCATION: "/config.json"
    ports:
      - <exposed-port>:80 # define the port the Connector should listen to on the host
    volumes:
      - <path-to-config-file>/config.json:/config.json:ro
    #   - </folder/of/your/choice>:/var/log/enmeshed-connector # select an existing directory of your choice where your log files should be saved
    depends_on:
      - ferretdb
    restart: on-failure

  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ferretdb
    restart: on-failure

  ferretdb:
    image: ghcr.io/ferretdb/ferretdb:latest
    container_name: ferretdb
    restart: on-failure
    environment:
      FERRETDB_POSTGRESQL_URL: postgres://user:password@postgres:5432/ferretdb
      FERRETDB_TELEMETRY: disable
      FERRETDB_LOG_LEVEL: error
    depends_on:
      - postgres

volumes:
  mongodb_data:
