@startuml Connector_ReceiveRelationshipRequest
!include ../../assets/plantuml/styles.iuml

title Connector: Receive Relationship Request
caption Copyright 2021, j&s-soft AG

box "Organizations's Infrastructure"
participant "Business\nSystem" as backend
participant "Enmeshed\nConnector" as connector
end box
participant "Enmeshed\nBackbone" as backbone

== Prerequisites ==
backbone <-> connector: Verified enmeshed Organization Identity


== Receive Relationship Request ==

backbone <- ++: Incoming request
backbone -> connector ++: Forward request
connector --> backbone: Received
backbone -> --: Request received

connector -> connector: Decrypt request with\ntemplate key

connector -> connector: Validate request

connector -> backend ++: Forward request
connector--

backend -> backend: Validate request

<- backend --: Forward request

@enduml