@startuml Create Template
!include ../../assets/plantuml/styles.iuml




box "Organizations's Infrastructure"
participant "Business\nSystem" as backend
participant "Enmeshed\nConnector" as connector
end box
participant "Enmeshed\nPlatform" as backbone
participant "Enmeshed\nApp" as app
actor "User" as user

== Prerequisites ==
backbone <--> connector: Verified Enmeshed Corporate Identity
connector <--> user: Existing Enmeshed Relationship


== Template ==







@enduml