@startuml Core_CreateAuthToken
!include ../.plantuml/skins/sequence_diagram.iuml

actor "User" as user
box "Consumer Landscape"
    participant "enmeshed\nApp" as App
    participant "Browser" as browser
end box
participant "enmeshed\nPlatform" as platform
box "Customer Landscape"
    participant "Website" as website
    participant "enmeshed\nConnector" as Connector
end box

== Prerequisites ==

App <--> Connector: enmeshed Relationship
website <--> Connector: enmeshed Integration

autonumber

== Login from App ==
user -> App ++: Open Customer\nWebsite
App -> platform ++: Get timestamp
platform --> app--: Returns timestamp and random id
note right
We have to ensure that
the provided signature
of the consumer was not
created in the past.

Thus, the trusted enmeshed
platform creates the
timestamps.
end note
App -> App: Signs random id
App -> App: Creates login token
App -> browser ++: Open Browser\nwith login token
App --
browser -> website++: Open Website with login token
website -> Connector++: Check login token
Connector -> Connector: Verify token\nsignature
Connector -> platform++: Check random id
platform --> Connector --: OK
Connector -> website --: Login OK\nenmeshed Address xyz
browser <--> website: Login Session for enmeshed Address xyz






@enduml