@startuml Create Template
!include ../../assets/plantuml/styles.iuml




box "Organization's Infrastructure"
participant "Website" as website
participant "Business\nSystem" as backend
participant "enmeshed\nConnector" as Connector
end box
participant "enmeshed\nBackbone" as Backbone
participant "enmeshed\nApp" as App
actor "User" as user

== Rahmenbedinungen ==
Backbone <-> Connector: enmeshed Connector hat eine\ndigitale Identität der Organisation.\nenmeshed Plattform kennt diese.
Connector <-> backend: Bestehende Systeme sind\nüber Integrationsmodule\nmit enmeshed Connector verbunden


== enmeshed Onboarding ==

user -> website: Möchte enmeshed Verknüpfung
activate website
website -> backend: enmeshed Verknüpfung eingehen
activate backend
backend -> Connector: Generiere Template für Nutzer\n(mit Nutzerdaten & Random Token)
backend -> backend: Verknüpft Random Token\nund SessionID
activate Connector
Connector -> Connector: Template erzeugen\n& verschlüsseln
Connector -> Backbone: Verschlüsseltes Template\nregistrieren\n(Löschung nach x Minuten)
activate Backbone
Backbone --> Connector: OK
deactivate Backbone
Connector --> backend: Template + Schlüssel\n(z.B. QR-Code/Link)
deactivate Connector
backend --> website: QR-Code und Link
deactivate backend
website --> user: QR-Code und Link


user -> App: Installiert & startet enmeshed App
activate App
App -> App: Erstellt Identität\n(falls keine vorhanden)
App -> Backbone: Registriert Identität
activate Backbone
Backbone -> App: OK
deactivate Backbone
App --> user: Lauffähig
user -> App: Scan QR-Code
App -> App: Lese QR-Code\n(TemplateId & Schlüssel)
App -> Backbone: Lade Template
activate Backbone
Backbone -> App: Rückgabe Template
deactivate Backbone
App -> App: Entschlüsselung\nTemplate
App --> user: Anzeige Template
user -> App: Annahme Template
App -> App: Daten aufbereiten\nenmeshed Adresse\nevtl. Daten des Nutzers
App -> App: Beziehung vorbereiten
App -> App: Anfrage verschlüsseln
App -> Backbone: Anfrage senden
activate Backbone
Backbone --> App: OK
App --> user: OK (müssen auf Annahme warten)
deactivate App
Backbone -> Connector: Anfrage senden
deactivate Backbone
activate Connector
Connector -> Connector: Anfrage entschlüsseln
Connector -> Connector: Anfrage prüfen
Connector -> backend: Anfrage weitergeben
activate backend
backend -> backend: Mapping enmeshed Adresse\nmit RandomToken\nmit UserID
backend -> website: enmeshed Anfrage angekommen
website -> user: enmeshed Anfrage angekommen
backend --> Connector: OK
deactivate backend
Connector -> Connector: Beziehung vorbereiten
Connector -> Connector: Annahme verschlüsseln
Connector -> Backbone: Annahme versenden
activate Backbone
Backbone --> Connector: OK
Connector -> backend: Angenommen
activate backend
backend -> website: Angenommen
deactivate backend
Backbone -> App: Annahme
deactivate Backbone
activate App
App -> App: Annahme entschlüsseln
App -> App: Annahme prüfen
App <--> Connector: Hello World








@enduml