@startuml Connector_CreateTemplate
!include ../../assets/plantuml/styles.iuml

title Connector: Create Template
caption Copyright 2021, j&s-soft AG

box "Organizations's Infrastructure"
participant "Business\nSystem" as backend
participant "enmeshed\nConnector" as Connector
end box
participant "enmeshed\nBackbone" as backbone

== Prerequisites ==
backbone <-> Connector: Verified enmeshed Organization Identity


== Create Template ==

-> backend ++: Start\n(with User)
backend -> backend: Create template content\nfor User
backend -> Connector ++: POST /RelationshipTemplates\n- content\n- expiresAt\n- maxNumberOfAllocations
Connector -> Connector: Validate input
Connector -> Connector: Encrypt template content\nwith random key
Connector -> backbone ++: Create template\n- templateCipher\n- expiresAt\n- maxNumberOfAllocations
backbone -> backbone: Store template
backbone --> Connector --: Returns templateId
Connector --> backend --: Returns template
backend --> Connector ++: POST /RelationshipTemplates/\n{templateId}/Token
Connector -> Connector: Create token content
Connector -> Connector: Encrypt token content with\nrandom key
Connector -> backbone ++: Create token\n- tokenCipher\n- expiresAt
backbone -> backbone: Store token
backbone --> Connector --: tokenId
Connector -> Connector: Create tokenReference
Connector --> backend: Returns token, tokenReference
<-- backend --: Stop\n(with template & \ntoken for User)

@enduml