@startuml Connector_CreateRelationshipRequest
!include ../../assets/plantuml/styles.iuml

title Connector: Create Relationship Request
caption Copyright 2021, j&s-soft AG

box "Organizations's Infrastructure"
participant "Business\nSystem" as backend
participant "Enmeshed\nConnector" as connector
end box
participant "Enmeshed\nBackbone" as backbone

== Prerequisites ==
backbone <-> connector: Verified enmeshed Organization Identity


== Create Relationship Request ==

-> backend ++: Start\n(with requestContent,\ntemplateId)
backend -> backend: Validate content
backend -> connector ++: POST /RelationshipRequests\n- requestContent\n- templateId
connector -> connector: Validate input
connector -> connector: Prepare request
connector -> connector: Encrypt request content\nwith template exchange key
connector -> backbone ++: Create RelationshipRequest\n- requestCipher
backbone -> backbone: Store request
backbone --> connector: Returns requestId
backbone -> --: Communicate to\nother party
connector --> backend: Returns request
<-- backend --: Stop\n(with Request)

@enduml