@startuml Connector_ReceiveMessage
!include ../../assets/plantuml/styles.iuml

title Connector: Receive Message
caption Copyright 2021, j&s-soft AG

box "Organizations's Infrastructure"
participant "Business\nSystem" as backend
participant "enmeshed\nConnector" as Connector
end box
participant "enmeshed\nBackbone" as backbone
actor "Sender" as user

activate Connector
== Prerequisites ==
backbone <-> Connector: Verified enmeshed Organization Identity
Connector <-> user: Existing enmeshed Relationship



== Receive Message ==


Connector -> backbone ++: Regularly check for updates
backbone --> Connector --: no updates

...

backbone <- user ++: Message to Connector
backbone --> user --: Random <messageId>

...

Connector -> backbone ++: Regularly check for updates
backbone --> Connector: New message <messageId>
Connector -> backbone: Fetch <messageId>
backbone --> user: <messageId> received\nby Recipient
backbone --> Connector --: message


Connector -> Connector: Decrypt message

Connector -> Connector: Validate message

alt
    Connector <--> backend: Webhook enabled
    Connector -> backend ++: Forward message via webhook
    backend -> backend: Process message
    deactivate backend
    |||
end

alt
    Connector <--> backend: Long-polling enabled
    activate backend
    loop
        backend -> Connector: POST /Synchronize
        Connector --> backend: Received changes
        backend -> backend: Process changes
        deactivate backend
        |||
    end
end

@enduml