@startuml Create Template
!include ../../assets/plantuml/styles.iuml




box "Organization's Infrastructure"
participant "Website" as website
participant "Business\nSystem" as backend
participant "enmeshed\nConnector" as Connector
end box
participant "enmeshed\nBackbone" as backbone
participant "enmeshed\nApp" as app
actor "User" as user

== Rahmenbedinungen ==
backbone <-> Connector: enmeshed Connector hat eine\ndigitale Identität der Organisation.\nenmeshed Plattform kennt diese.
Connector <-> backend: Bestehende Systeme sind\nüber Integrationsmodule\nmit enmeshed Connector verbunden


== enmeshed Onboarding ==

user -> website: Möchte enmeshed Verknüpfung
activate website
website -> backend: enmeshed Verknüpfung eingehen
activate backend
backend -> Connector: Generiere Template für Nutzer\n(mit Nutzerdaten & Random Token)
backend -> backend: Verknüpft Random Token\nund SessionID
activate Connector
Connector -> Connector: Template erzeugen\n& verschlüsseln
Connector -> backbone: Verschlüsseltes Template\nregistrieren\n(Löschung nach x Minuten)
activate backbone
backbone --> Connector: OK
deactivate backbone
Connector --> backend: Template + Schlüssel\n(z.B. QR-Code/Link)
deactivate Connector
backend --> website: QR-Code und Link
deactivate backend
website --> user: QR-Code und Link


user -> app: Installiert & startet enmeshed App
activate app
app -> app: Erstellt Identität\n(falls keine vorhanden)
app -> backbone: Registriert Identität
activate backbone
backbone -> app: OK
deactivate backbone
app --> user: Lauffähig
user -> app: Scan QR-Code
app -> app: Lese QR-Code\n(TemplateId & Schlüssel)
app -> backbone: Lade Template
activate backbone
backbone -> app: Rückgabe Template
deactivate backbone
app -> app: Entschlüsselung\nTemplate
app --> user: Anzeige Template
user -> app: Annahme Template
app -> app: Daten aufbereiten\nenmeshed Adresse\nevtl. Daten des Nutzers
app -> app: Beziehung vorbereiten
app -> app: Anfrage verschlüsseln
app -> backbone: Anfrage senden
activate backbone
backbone --> app: OK
app --> user: OK (müssen auf Annahme warten)
deactivate app
backbone -> Connector: Anfrage senden
deactivate backbone
activate Connector
Connector -> Connector: Anfrage entschlüsseln
Connector -> Connector: Anfrage prüfen
Connector -> backend: Anfrage weitergeben
activate backend
backend -> backend: Mapping enmeshed Adresse\nmit RandomToken\nmit UserID
backend -> website: enmeshed Anfrage angekommen
website -> user: enmeshed Anfrage angekommen
backend --> Connector: OK
deactivate backend
Connector -> Connector: Beziehung vorbereiten
Connector -> Connector: Annahme verschlüsseln
Connector -> backbone: Annahme versenden
activate backbone
backbone --> Connector: OK
Connector -> backend: Angenommen
activate backend
backend -> website: Angenommen
deactivate backend
backbone -> app: Annahme
deactivate backbone
activate app
app -> app: Annahme entschlüsseln
app -> app: Annahme prüfen
app <--> Connector: Hello World








@enduml