@startuml Connector_PreRelationshipOverview
!include ../../assets/plantuml/styles.iuml


title Connector: Pre-Relationship Overview

footer Page %page% of %lastpage%
caption Copyright 2021, j&s-soft AG

box "Organizations's Infrastructure"
participant "enmeshed\nApp" as app
participant "Browser" as browser
end box
box "Organizations's Infrastructure"
participant "Business\nSystem" as backend
participant "enmeshed\nConnector" as Connector
end box
participant "enmeshed\nBackbone" as backbone




== Prerequisites ==
backbone <-> Connector: Verified enmeshed Organization Identity


== Pre-Relationship ==

-> browser++: Open Browser & Navigate
browser -> backend ++: Opens Website
backend <-> browser --: Websites & Session

browser -> backend ++: \nLogin/Upgrade/Onboard

backend -> backend: Create content\nfor user

backend -> Connector ++: \nCreate Template\nwith content & QR-Code

Connector -> backbone ++: Submit Template
backbone --> Connector --: templateId
Connector --> backend --: template, QR-Code


backend --> browser: Render QR-Code/Link
backend --
-> app ++: Open App

app -> browser: Scans QR-Code/ \nopens Link
browser --> app: Content
browser --
app -> backbone++: \nFetch Token & Template
backbone --> app--: Returns Token & Template
app -> app: Show template with\npre-filled data

newpage

-> app: \nAccept template
app -> app: Bundle user content
app -> backbone ++: Submit RelationshipRequest with user content
backbone -> app : RelationshipRequest
backbone -> connector--: RelationshipRequest
Connector ++
Connector -> backend++: New RelationshipRequest\ncontaining user details
Connector --
backend --> browser: Got request
backend -> backend: Validate content\n& create response
backend -> Connector ++: Accept Request\nwith response
Connector -> backbone ++: Accept Request\nwith response
backbone --> Connector: Relationship

Connector --> backend: Relationship
Connector --
backend --> browser: Got relationship
backend --

backbone --> app: Relationship
backbone --
app --

== Outcome ==
browser <--> backend: Knowledge of\nenmeshed Relationship
app <--> Connector: Trusted, bi-directional enmeshed relationship

@enduml