@startuml Connector_GetOpenRelationshipRequests
!include ../../assets/plantuml/styles.iuml

title Connector: Get Open Relationship Requests
caption Copyright 2021, j&s-soft AG

box "Organizations's Infrastructure"
participant "Business\nSystem" as backend
participant "enmeshed\nConnector" as Connector
end box
participant "enmeshed\nBackbone" as Backbone

== Prerequisites ==
Backbone <-> Connector: Verified enmeshed Organization Identity


== Get Open Relationship Requests ==

-> backend ++: Start
backend -> Connector ++: GET /RelationshipRequests\n/OpenIncoming

Connector -> Backbone ++: Get relationship requests
Backbone -> Backbone: Retrieve requests
Backbone --> Connector --: Returns requests

Connector -> Connector: Decrypt every request
Connector -> Connector: Validate every request

Connector --> backend --: Returns requests

<-- backend --: Stop\n(with Requests)

@enduml