@startuml Connector_GetTemplate
!include ../../assets/plantuml/styles.iuml

title Connector: Get Template
caption Copyright 2021, j&s-soft AG

box "Organizations's Infrastructure"
participant "Business\nSystem" as backend
participant "enmeshed\nConnector" as Connector
end box
participant "enmeshed\nBackbone" as backbone

== Prerequisites ==
backbone <-> Connector: Verified enmeshed Organization Identity


== Get Template ==

-> backend ++: Start\n(with truncatedReference)
backend -> Connector ++: POST /RelationshipTemplates\n- truncatedReference
Connector -> Connector: Validate input
Connector -> Connector: Extract tokenId and secretKey\nout of reference
Connector -> Connector: Validate tokenId and secretKey
Connector -> backbone ++: Get token\n- tokenId
backbone -> backbone: Retrieve token
backbone --> Connector --: Returns token

Connector -> Connector: Decrypt token\nwith secretKey
Connector -> Connector: Validate token
Connector -> Connector: Extract templateId and templateKey\nout of token

Connector -> backbone ++: Get template\n- templateId
backbone -> backbone: Retrieve template
backbone --> Connector --: Returns template
Connector -> Connector: Decrypt template\nwith templateKey
Connector -> Connector: Validate template

Connector --> backend: Returns template
<-- backend --: Stop\n(with Template)

@enduml