@startuml Connector_GetTemplate
!include ../../assets/plantuml/styles.iuml

title Connector: Get Template
caption Copyright 2021, j&s-soft AG

box "Organizations's Infrastructure"
participant "Business\nSystem" as backend
participant "enmeshed\nConnector" as Connector
end box
participant "enmeshed\nBackbone" as Backbone

== Prerequisites ==
Backbone <-> Connector: Verified enmeshed Organization Identity


== Get Template ==

-> backend ++: Start\n(with reference.truncated)
backend -> Connector ++: POST /RelationshipTemplates\n- reference.truncated
Connector -> Connector: Validate input
Connector -> Connector: Extract tokenId and secretKey\nout of reference
Connector -> Connector: Validate tokenId and secretKey
Connector -> Backbone ++: Get token\n- tokenId
Backbone -> Backbone: Retrieve token
Backbone --> Connector --: Returns token

Connector -> Connector: Decrypt token\nwith secretKey
Connector -> Connector: Validate token
Connector -> Connector: Extract templateId and templateKey\nout of token

Connector -> Backbone ++: Get template\n- templateId
Backbone -> Backbone: Retrieve template
Backbone --> Connector --: Returns template
Connector -> Connector: Decrypt template\nwith templateKey
Connector -> Connector: Validate template

Connector --> backend: Returns template
<-- backend --: Stop\n(with Template)

@enduml