@startuml Create Template
!include ../../assets/plantuml/styles.iuml




box "Organizations's Infrastructure"
participant "Business\nSystem" as backend
participant "enmeshed\nConnector" as Connector
end box
participant "enmeshed\nPlatform" as backbone
participant "enmeshed\nApp" as app
actor "User" as user

== Prerequisites ==
backbone <--> Connector: Verified enmeshed Corporate Identity
Connector <--> user: Existing enmeshed Relationship


== Template ==







@enduml