@startuml Connector_CreateRelationshipRequest
!include ../../assets/plantuml/styles.iuml

title Connector: Create Relationship Request
caption Copyright 2021, j&s-soft AG

box "Organizations's Infrastructure"
participant "Business\nSystem" as backend
participant "enmeshed\nConnector" as Connector
end box
participant "enmeshed\nBackbone" as Backbone

== Prerequisites ==
Backbone <-> Connector: Verified enmeshed Organization Identity


== Create Relationship Request ==

-> backend ++: Start\n(with requestContent,\ntemplateId)
backend -> backend: Validate content
backend -> Connector ++: POST /RelationshipRequests\n- requestContent\n- templateId
Connector -> Connector: Validate input
Connector -> Connector: Prepare request
Connector -> Connector: Encrypt request content\nwith template exchange key
Connector -> Backbone ++: Create RelationshipRequest\n- requestCipher
Backbone -> Backbone: Store request
Backbone --> Connector: Returns requestId
Backbone -> --: Communicate to\nother party
Connector --> backend: Returns request
<-- backend --: Stop\n(with Request)

@enduml