@startuml Connector_AcceptRelationshipRequest
!include ../../assets/plantuml/styles.iuml

title Connector: Accept Relationship Request
caption Copyright 2021, j&s-soft AG

box "Organizations's Infrastructure"
participant "Business\nSystem" as backend
participant "enmeshed\nConnector" as Connector
end box
participant "enmeshed\nBackbone" as Backbone

== Prerequisites ==
Backbone <-> Connector: Verified enmeshed Organization Identity


== Accept Relationship Request ==

-> backend ++: Start\n(with requestId,\nresponse content)
backend -> backend: Validate content
backend -> Connector ++: PUT /RelationshipRequests/\n{requestId}/Accept\n- response content
Connector -> Connector: Validate input
Connector -> Connector: Encrypt response content\nwith request key
Connector -> Backbone ++: Create RelationshipRequestResponse\n- responseCipher
Backbone -> Backbone: Store request response
Backbone --> Connector: Returns relationshipId
Backbone -> --: Forward response

Connector --> backend --: Returns relationship
<-- backend --: Stop\n(with relationship)
@enduml