@startuml Test

!includeurl  https://raw.githubusercontent.com/nmshd/nmshd.github.io/main/diagrams/styles.iuml

participant "App" as app
participant "Backbone" as backbone

app -> backbone: Test2

@enduml
