@startuml Connector_AcceptRelationshipRequest
!include ../../assets/plantuml/styles.iuml

title Connector: Accept Relationship Request
caption Copyright 2021, j&s-soft GmbH

box "Organizations's Infrastructure"
participant "Business\nSystem" as backend
participant "Enmeshed\nConnector" as connector
end box
participant "Enmeshed\nBackbone" as backbone

== Prerequisites ==
backbone <-> connector: Verified enmeshed Organization Identity


== Accept Relationship Request ==

-> backend ++: Start\n(with requestId,\nresponse content)
backend -> backend: Validate content
backend -> connector ++: PUT /RelationshipRequests/\n{requestId}/Accept\n- response content
connector -> connector: Validate input
connector -> connector: Encrypt response content\nwith request key
connector -> backbone ++: Create RelationshipRequestResponse\n- responseCipher
backbone -> backbone: Store request response
backbone --> connector: Returns relationshipId
backbone -> --: Forward response

connector --> backend --: Returns relationship
<-- backend --: Stop\n(with relationship)
@enduml