blank_issues_enabled: false
contact_links:
  - name: Enmeshed Issue Tracker
    url: https://github.com/nmshd/feedback/issues
    about: Open bug reports and feature requests.
  - name: Enmeshed Discussions
    url: https://github.com/nmshd/feedback/discussions
    about: Share your feedback with the Enmeshed team.
