@startuml Connector_SendMessage
!include ../../assets/plantuml/styles.iuml

title Connector: Send Message
caption Copyright 2021, j&s-soft GmbH

box "Organizations's Infrastructure"
participant "Business\nSystem" as backend
participant "Enmeshed\nConnector" as connector
end box
participant "Enmeshed\nBackbone" as backbone
actor "Recipient" as user

== Prerequisites ==
backbone <-> connector: Verified enmeshed Organization Identity
connector <-> user: Existing enmeshed Relationship

== Send Message ==

-> backend ++: Start\n(with recipients,\ncontent)
backend -> backend: Validate input
backend -> connector ++: POST /Messages\n- recipients\n- content
connector -> connector: Validate input
connector -> connector: Encrypt message for every recipient
connector -> backbone ++: Create Message\n- messageCipher
backbone -> backbone: Store message
backbone --> connector: Returns messageId, timestamp
backbone -> user--: Forward message

connector --> backend --: Returns message
<-- backend --: Stop\n(with message)

@enduml