name: Test

on:
  push:
    branches-ignore:
      - main
  pull_request_target:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npx prettier -c .
      - run: npm audit
      - run: npx markdownlint-cli **/*.md
