name: Test

on:
  push:
    branches-ignore:
      - main

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npx prettier -c .
      - run: npm audit
      - run: npx markdownlint-cli **/*.md
