name: Test

on:
  push:
    branches-ignore: [main, release/**]
  pull_request_target:
    types: [opened, synchronize, reopened]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  compile:
    runs-on: ubuntu-latest
    container:
      image: jekyll/jekyll
    steps:
      - uses: actions/checkout@v2
      - run: npx prettier -c .
      - run: npm audit
      - run: npx markdownlint-cli **/*.md
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: bundle exec jekyll build
